[build]
  publish = "."
  command = "echo \"window.API_BASE = '${API_BASE:-}';\" > env.js && echo 'Build complete'"

[[redirects]]
  from = "/"
  to = "/multiuser_client.html"
  status = 200
  force = true

[[redirects]]
  from = "/index.html"
  to = "/multiuser_client.html"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/env.js"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
