[build]
  publish = "."
  command = "echo \"window.API_BASE = '${API_BASE:-}';\" > env.js && echo 'Build complete'"

[[redirects]]
  from = "/"
  to = "/multiuser_client.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=0, must-revalidate"
